apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-sample
  labels:
    app: busybox-sample
spec:
  replicas: 1
  template:
    metadata:
      name: busybox-sample
      labels:
        app: busybox-sample
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: busybox-sample
        image: busybox
        resources:
          limits:
            cpu: 1
            memory: 800M
          requests:
            cpu: .1
            memory: 300M
        ports:
          - containerPort: 80
  selector:
    matchLabels:
      app: busybox-sample